classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0MTHxEjwoCSi+0gkcSKGjCdfK/yPuBgli2PgLTuWIV7vuni3DX+83VyqIAlomfSu1AXtmA8qej7vcO3N8YQUDwJiLfBhrMGvPs9zRxRhBtEnI8aKPxW7Svqhtoo9T5WnnxsLqti0VkOI5jyAORm2s1eCER91FnAC2JP3hj6nqoZOK9kPzZYX44f5oCHG3Tqo2cIFXcYUp2N4SZRkhYMSRN5+u7YVSFugXFoBH9xbNxgrp8X/whwCTx3J4Ki2Go77RQcyc8JslNF9MlhH0ACTA39o7bXfiZ9dSIrwYK2oE+b5Olpt+7WAsPWK7f42rHZga46zMbluJOgKp4BS1e44D
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0MTHxEjwoCSi+0gkcSKGjCdfK/yPuBgli2PgLTuWIV7vuni3DX+83VyqIAlomfSu1AXtmA8qej7vcO3N8YQUDwJiLfBhrMGvPs9zRxRhBtEnI8aKPxW7Svqhtoo9T5WnnxsLqti0VkOI5jyAORm2s1eCER91FnAC2JP3hj6nqoZOK9kPzZYX44f5oCHG3Tqo2cIFXcYUp2N4SZRkhYMSRN5+u7YVSFugXFoBH9xbNxgrp8X/whwCTx3J4Ki2Go77RQcyc8JslNF9MlhH0ACTA39o7bXfiZ9dSIrwYK2oE+b5Olpt+7WAsPWK7f42rHZga46zMbluJOgKp4BS1e44D
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
