classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAq0qBd3yX5DnsJLXMT1Xsf+oyQ0PvAWAPZWdpa1T7leRF0/yY824uUH+zDAKk1qeLjhqNxsavNc277sQBcTjzgd+Mpej86rugE1XUAfA0kAMavYeqW8Wc3N4Z86Wqg2Sbo+F9wajgQ11bTlycnsSdnknF9wKAHJI09y2L4e5HcorxdKfqLsLSx9TF2s9MrI4bk2CYAqBkp6mqTbfmImX+1aWGa/bGKE/8ha1TsnKes+LrSXBb7yqVcN2ajeAhaKWDRD1MAM3aMl6bG+PM//4wdsj7YOdM+e151lXYoGA9Y9IKPEpIdFFKXyi0kppgRu9XZeqpugdY7cTIhtjoaJLt
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAq0qBd3yX5DnsJLXMT1Xsf+oyQ0PvAWAPZWdpa1T7leRF0/yY824uUH+zDAKk1qeLjhqNxsavNc277sQBcTjzgd+Mpej86rugE1XUAfA0kAMavYeqW8Wc3N4Z86Wqg2Sbo+F9wajgQ11bTlycnsSdnknF9wKAHJI09y2L4e5HcorxdKfqLsLSx9TF2s9MrI4bk2CYAqBkp6mqTbfmImX+1aWGa/bGKE/8ha1TsnKes+LrSXBb7yqVcN2ajeAhaKWDRD1MAM3aMl6bG+PM//4wdsj7YOdM+e151lXYoGA9Y9IKPEpIdFFKXyi0kppgRu9XZeqpugdY7cTIhtjoaJLt
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
