classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKLwpEZJY6qYn051FDwiIoQCycDOEa4nkvAjB0cNucmB0+AEA3xA+tLrINE/ehbm0L1acCelfLqrkIi6O9SxK4wKiwRLdBb4m4MXHuvIkNilAv4i+9EAnYHwU6T5FIgX52vnu5bOJJad+3ULHTOrm/uS76BgFqu7qUiF6snQrpdGCpOJRW4hpKVMYuBoJoRKtBklhfgb7mIOrGT0tdTF9OwOKoSYAj1AgVjAluQSZgPC/C2rLzx1hUF5E7IyuTyH2LU0G7Jauw+9cxUpvYjfdZJClpI3ZHUAFqTA5QTH0S34haZUt92H/UdBCq6coU4Xux/roF4gR7d13hufY8Bvy/
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKLwpEZJY6qYn051FDwiIoQCycDOEa4nkvAjB0cNucmB0+AEA3xA+tLrINE/ehbm0L1acCelfLqrkIi6O9SxK4wKiwRLdBb4m4MXHuvIkNilAv4i+9EAnYHwU6T5FIgX52vnu5bOJJad+3ULHTOrm/uS76BgFqu7qUiF6snQrpdGCpOJRW4hpKVMYuBoJoRKtBklhfgb7mIOrGT0tdTF9OwOKoSYAj1AgVjAluQSZgPC/C2rLzx1hUF5E7IyuTyH2LU0G7Jauw+9cxUpvYjfdZJClpI3ZHUAFqTA5QTH0S34haZUt92H/UdBCq6coU4Xux/roF4gR7d13hufY8Bvy/
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
