classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEtmz39APenGjNdoRxvy4JnfaNUvTAKSp/Tjnj+Xr/KfLR5U6U4dECEJvR0Pn7PnDNw/RAuB5HPYYfNSCq2vZw7k65k36GzYcklqVqM2X40mmlHZ8ASbvj3BtoPksCpGVGiIbRvGirAEowCz0px2/KjiOl3lCWhs0IOWv2pu+PDypQbfZN6G0wJObPLPnikpQMaKwDSaGPT0QC9tgzOr2/kDFSmb/PrQ336u/fhsLwjAv8Lm9W3r/JMLHjFPS5wPuOUEPgQrul1R5r20+MSFCkwz/AIyUe3DvUx4EkTQIxxTA8OQw+DzuyeMd+fxW2WLwPap7XtLWDTfN83B6CYbEl
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEtmz39APenGjNdoRxvy4JnfaNUvTAKSp/Tjnj+Xr/KfLR5U6U4dECEJvR0Pn7PnDNw/RAuB5HPYYfNSCq2vZw7k65k36GzYcklqVqM2X40mmlHZ8ASbvj3BtoPksCpGVGiIbRvGirAEowCz0px2/KjiOl3lCWhs0IOWv2pu+PDypQbfZN6G0wJObPLPnikpQMaKwDSaGPT0QC9tgzOr2/kDFSmb/PrQ336u/fhsLwjAv8Lm9W3r/JMLHjFPS5wPuOUEPgQrul1R5r20+MSFCkwz/AIyUe3DvUx4EkTQIxxTA8OQw+DzuyeMd+fxW2WLwPap7XtLWDTfN83B6CYbEl
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
