
classes:
- system.linux.system.repo.mcp.apt_mirantis.maas
- system.maas.region.single
- cluster.training-lab.infra
parameters:
  _param:
    maas_region_port: 5240
    maas_cluster_region_port: ${_param:maas_region_port}
  maas:
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}:${_param:maas_region_port}
    cluster:
      region:
        host: ${_param:deploy_address}:${_param:maas_cluster_region_port}
    # subnets:
    #   deploy_network:
    #     cidr: 10.0.0.0/24
    #     fabric: deploy_network
    #     gateway_ip: 10.0.0.11
    #     iprange:
    #       end: 10.0.0.254
    #       start: 10.0.0.250
    # fabrics:
    #   deploy_network:
    #     description: Fabric for deploy_network
    # machines:
    #   machine1_new_schema:
    #     pxe_interface_mac: "11:22:33:44:55:66"
    #     interfaces:
    #       nic01:
    #         type: eth # NotImplemented
    #         name: eth0 # Override default nic name. Interface to rename will be identified by mac
    #         mac: "11:22:33:44:55:66"
    #         mode: "static"
    #         ip: "2.2.3.19"  # ip should be out of reserved subnet range, but still in subnet range
    #         subnet: "subnet1"
    #         gateway: "2.2.3.2" # override default gateway from subnet
    #       nic02:
    #         type: eth # Not-implemented
    #         mac: "11:22:33:44:55:78"
    #         subnet: "subnet2"
    #         mode: "dhcp"
    #     power_parameters:
    #       power_type: virsh
    #       power_address: '192.168.250.12'
    #       power_id: "vm-pxe-ruzickap-01-kvm01"


# linux:
#   network:
#     interface:
#       primary_interface:
#         enabled: true
#         name: ens2
#         type: eth
#         proto: static
#         netmask: ${_param:deploy_network_netmask}
#         address: ${_param:single_address}
#         gateway: ${_param:deploy_network_gateway}
#         name_servers:
#         - ${_param:dns_server01}
#         - ${_param:dns_server02}
### Sample MaaS Configuration
#  maas:
#    region:
#      subnets:
#        deploy_network:
#          cidr: 172.17.44.0/24
#          fabric: deploy_network
#          gateway_ip: 172.17.44.1
#          iprange:
#            end: 172.17.44.200
#            start: 172.17.44.92
#      fabrics:
#        deploy_network:
#          description: Fabric for deploy_network
#      machines:
#        kvm02:
#          interface:
#            mac: 00:25:90:eb:92:4a
#          power_parameters:
#            power_address: ipmi_ip
#            power_password: password
#            power_type: ipmi
#            power_user: engineer
