
classes:
- system.linux.system.repo.mcp.apt_mirantis.maas
- system.maas.region.single
- cluster.training-lab.infra
parameters:
  _param:
    maas_region_port: 5240
    maas_cluster_region_port: ${_param:maas_region_port}
  maas:
    cluster:
      region:
        host: ${_param:deploy_address}:${_param:maas_cluster_region_port}
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}:${_param:maas_region_port}
      fabrics:
        deploy_network:
          description: Fabric for deploy_network
      machines:
        vm-pxe1-ruzickap-01-kvm01:
          pxe_interface_mac: 52:54:00:00:A1:A1
          power_parameters:
            power_address: qemu+tcp://10.0.0.11/system
            power_type: virsh
        vm-pxe2-ruzickap-01-kvm01:
          pxe_interface_mac: 52:54:00:00:A1:A2
          power_parameters:
            power_address: qemu+tcp://10.0.0.11/system
            power_type: virsh
        vm-pxe3-ruzickap-01-kvm01:
          pxe_interface_mac: 52:54:00:00:A1:A3
          power_parameters:
            power_address: qemu+tcp://10.0.0.11/system
            power_type: virsh
        vm-pxe1-ruzickap-01-kvm02:
          pxe_interface_mac: 52:54:00:00:A2:A1
          power_parameters:
            power_address: qemu+tcp://10.0.0.12/system
            power_type: virsh
        vm-pxe2-ruzickap-01-kvm02:
          pxe_interface_mac: 52:54:00:00:A2:A2
          power_parameters:
            power_address: qemu+tcp://10.0.0.12/system
            power_type: virsh
        vm-pxe3-ruzickap-01-kvm02:
          pxe_interface_mac: 52:54:00:00:A2:A3
          power_parameters:
            power_address: qemu+tcp://10.0.0.12/system
            power_type: virsh
        vm-pxe1-ruzickap-01-kvm03:
          pxe_interface_mac: 52:54:00:00:A3:A1
          power_parameters:
            power_address: qemu+tcp://10.0.0.13/system
            power_type: virsh
        vm-pxe2-ruzickap-01-kvm03:
          pxe_interface_mac: 52:54:00:00:A3:A2
          power_parameters:
            power_address: qemu+tcp://10.0.0.13/system
            power_type: virsh
        vm-pxe3-ruzickap-01-kvm03:
          pxe_interface_mac: 52:54:00:00:A3:A3
          power_parameters:
            power_address: qemu+tcp://10.0.0.13/system
            power_type: virsh

# linux:
#   network:
#     interface:
#       primary_interface:
#         enabled: true
#         name: ens2
#         type: eth
#         proto: static
#         netmask: ${_param:deploy_network_netmask}
#         address: ${_param:single_address}
#         gateway: ${_param:deploy_network_gateway}
#         name_servers:
#         - ${_param:dns_server01}
#         - ${_param:dns_server02}
### Sample MaaS Configuration
#  maas:
#    region:
#      subnets:
#        deploy_network:
#          cidr: 172.17.44.0/24
#          fabric: deploy_network
#          gateway_ip: 172.17.44.1
#          iprange:
#            end: 172.17.44.200
#            start: 172.17.44.92
#      fabrics:
#        deploy_network:
#          description: Fabric for deploy_network
#      machines:
#        kvm02:
#          interface:
#            mac: 00:25:90:eb:92:4a
#          power_parameters:
#            power_address: ipmi_ip
#            power_password: password
#            power_type: ipmi
#            power_user: engineer
