parameters:
  _param:
    # MAAS
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    # OpenStack
    horizon_secret_key_generated: ZOHoY0QdBRxrBEnXNsqem7xrXRDlfulz0c5svspca5SRnv7ZWLLI8C3n4QFuluzg
    keystone_swift_password_generated: 0IbKLQTOTmtSBCjr
    rabbitmq_openstack_password_generated: LmfBjawy2q8zHQVV
    heat_domain_admin_password_generated: mSoCT0i6sP0sh2Tv
    ceilometer_influxdb_password_generated: YAPT8wiGK40jDJv7
    billometer_secret_key_generated: rGXFz33DTaFTw4Yay16M5W6CUmgFHKhOAqDotcEqynBpElcpaJFYezAh8RIY8kt6
    mysql_aodh_password_generated: Hj1d7jJhAvlKvI9m
    mysql_cinder_password_generated: H1Pd68DR0Ty0ed3T
    mysql_ceilometer_password_generated: gL7knNuEb76qlixN
    mysql_glance_password_generated: vw7SNA9sRei1L96N
    mysql_heat_password_generated: rLNuoS3OebsFZ1O0
    mysql_keystone_password_generated: yRUK10OAyQ6L9CGv
    mysql_neutron_password_generated: fXr74xPJ40VBkNuA
    mysql_nova_password_generated: sB1yND1chVyNaVgu
    keystone_service_token_generated: q4nvsMSkc6CuBivy
    keystone_admin_password_generated: Ezg3MnMMhpv3t8hq
    keystone_ceilometer_password_generated: NXYuSqbAGk9KbQoq
    keystone_cinder_password_generated: NN2a4ZHihDhF3a7P
    keystone_glance_password_generated: eVBH79zwf66a791k
    keystone_heat_password_generated: N4sVVnoHOiwflUgP
    keystone_keystone_password_generated: nx0Tegf23JvkAxBU
    keystone_neutron_password_generated: t9V9XHkkPOcu6HKe
    keystone_nova_password_generated: oTuasbIdf3JjJadk
    keystone_aodh_password_generated: 3sRhCrdOMi87x8OB
    ceilometer_secret_key_generated: AwFuWTSnA3lgqB5g
    mongodb_ceilometer_password_generated: 16hWHwXtYqktnQh8
    mongodb_admin_password_generated: CdHC42Otj7WoP8X1
    mongodb_shared_key_generated: 0TtQCBqlOrWHgSrf9bqufAkVR4SEZW705acNZNrORYfhEP1zZnmwZEvMmg1E3KK9
    openstack_metadata_password_generated: nfMGZr9qDLmldbHH
    keystone_billometer_password_generated: y7GO6hdMvkqAfFva
    cinder_storage_secret_uuid_generated: "9db5df50-a1ef-e2d9-2043-beaa6e09484f"
    nova_storage_secret_uuid_generated: "f0318f63-8145-2c34-be70-50119bd9ea00"
    # DriveTrain / CICD
    openldap_admin_password_generated: bdqB9MYPCscZkEdJ
    openldap_config_password_generated: k7yDaPFkCxVMcfnv
    openldap_readonly_password_generated: ZaAZRzWHUBg8kdKc
    jenkins_admin_password_generated: 5NGCRC7DABBYINdg
    gerrit_admin_password_generated: ZBU7SkGMhW3oeQPh
    cicd_keepalived_vip_password_generated: dlpNncv29akc5ouY
    cicd_mysql_admin_password_generated: 6MD2r6AGTpREcX45
    cicd_mysql_gerrit_password_generated: wp5FiJZ1JCtZYR2Q
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHEopy+0HmWK5BJlebgbovNU2XRf0ql5LvyPbrjkJpFt32EANeRII+RI1TUd401O/W3r5y9Ukg2pY4qGd+WQjrHiAx8/qw07VkUYoVLILuyKt5AnkKR3iGbtgXve37x66huMsf6JzGTTXY4klBxfeu8fmPp57FbDL+RyoXCtvF778HmPMDhTTIe/0CE5824QAb5RzBkJqD5AIJp15n8M8VxumCPIuE6pJI9xM1ILOB9BqzTRcpYo1hDvrtM452ElAnIbkvcYNev8aZngDT91kOW5aCkvoZ7HQavobGnY0ZHioduA+e30ZwG2Keo83lVGf2f6dKMj/XKHdvjOr5//Ez
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAxxKKcvtB5liuQSZXm4G6LzVNl0X9KpeS78j2645CaRbd9hAD
      XkSCPkSNU1HeNNTv1t6+cvVJINqWOKhnflkI6x4gMfP6sNO1ZFGKFSyC7sireQJ5
      Ckd4hm7YF73t+8euobjLH+icxk012OJJQcX3rvH5j6eexWwy/kcqFwrbxe+/B5jz
      A4U0yHv9AhOfNuEAG+UcwZCag+QCCadeZ/DPFcbpgjyLhOqSSPcTNSCzgfQas00X
      KWKNYQ767TOOdhJQJyG5L3GDXr/GmZ4A0/dZDluWgpL6Gex0Gr6Gxp2NGR4qHbgP
      nt9GcBtinqPN5VRn9n+nSjI/1yh3b4zq+f/xMwIDAQABAoIBAQDFskgEQDoFw/Pp
      h2ZhbMe1sj3ICR2OetDViMKO08xoCOmNQAHYUDj4FaQ0Jo2B8iXtQW/pQmbJVcrx
      oWyGMW2F8XkPorhHezgc1E1JEddFw8tmdWo3Jxsuhk3b5ia9cGSg/p/apGttE6hy
      JueRhkSfXHb2jwRCE13g4FOQZpwzSE+M9A0y63C5+95WxYQ+ZBBxtJI0RpYMtqer
      IMo4CrEeDR4m8CJ+9vr2X0xXtgOHkpH8ls+HMTiu0W7nEkUcHaOze8PeKnlfPY5I
      xSAkDhs1cJV5s90HLHHFsxoUxzayp6Gm/SWKJrf7s+jagsV/VLsGozY+Yw8Yrw4t
      2Y2dEDfBAoGBAOzJa1QO6P5HMukYtylvGW16LtShWtCW3DhpD5/gP8YGt+Xiv3OI
      tXuOU0gckSxv3PZlBQQydly/PH3XdbaJlJsxBT6uudSGEUq0w7R1vlc1Id+FeARX
      qL5KW8rWi3rz1W40UXOXuxbtSo+rTOpkhr2MNe0+VG2N9ia1UPxtb0/7AoGBANc5
      tiHUt0KdPdfAgHZU2FVjz/mUrqT8gmnBiXPzLehgnMW2HsQA08T474YXt666hm8/
      cRM9Z+Mo/woGFQWq3xkZzAUXe4kcVwPuuE9yeoZDeYS6E0Vz7/D2rXgcbxru7nAt
      D0VKszXnrwa4UxC+lIMlljAq0y4DaPJSpU0g8MYpAoGBAJaZHIwf14wyGG0sbQIL
      SS7Z8QMHhMz5xiKSn39djvIRv9CUQJPotRRaVxmcIbETjIOhiGk89w7SClU3PgTU
      yBFUQjO1yTcj9cd/5KDX6jFo95xENSr93bL5dBw0DA4tGue2mr9cF3/jd/KcTpUd
      Tp0rmfjEFcp/6biAxXtm1s8VAoGAKc8ZNWs4CmW3TMElc1c6CyRvk0Exx/URdG/X
      PsH/qgOSkMm3IkYy3TGqffb/hJ7RXK0LTzx/gN5G5PCXhtlRq3OacWbFZbYupSHr
      hetsJ8bVxVXMRpKmCr4wpoOHhcjiYsIuFDzVoWQXWQvXfwo2mV9k1IiNK4QYD/LE
      D76VZzkCgYB6j9fjS9WBkrZo4TuhvKSn355+Upn8SJDp46zVYaa+3PyeQh8d5Wa4
      IP2SVjhzlv88MQQ5fwzlM7Ct3N2ZeOKDZAKGygEIXsthSfVwYNR3tiyftchPNylW
      8biGaec52ZiDPYFcxoWMZQLB3GWOrIEJD5fETSvJONKU4GGBL3XhHw==
      -----END RSA PRIVATE KEY-----
    rabbitmq_admin_password_generated: UJCmM1bAQ8tqBNcA
    rabbitmq_secret_key_generated: ymOK4lHglYuM8abc
    galera_server_maintenance_password_generated: yBGUbV155bGcJ2da
    galera_server_admin_password_generated: iK8UCqKTZ3VBHhDT
    docker_registry_http_secret_generated: PjktgHoNaUO0uPTA
